In [ ]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [2]:
df = pd.read_excel('/content/drive/MyDrive/ML_Module_3/AdvertisingSpendvsSales.xlsx')
df

        TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [5]:
x = df[['TV', 'radio', 'newspaper']]
y = df['sales']

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ...
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: sales, Length: 200, dtype: float64

In [9]:
from sklearn import model_selection
x_train, x_test, y_train, y_test = model_selection.train_test_split(x, y, test_size=0.2)

len(x_test)

40

In [11]:
from sklearn import linear_model
lr = linear_model.LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [12]:
lr.predict(x_test)

array([ 7.81889508, 20.76962781,  8.86275663, 22.24407805, 14.52390354,
       15.35960759,  9.79069851,  9.92729088, 10.49893758, 12.30961788,
       10.63250155, 16.95619212, 10.17240997,  7.57818574, 10.44465369,
       12.09232271, 19.11286062, 21.29541751, 12.08060021, 21.54069941,
       16.30027361, 10.44866984, 18.37248986, 15.17610562, 14.6931806 ,
       15.57649279,  6.51786587, 13.25704806, 13.58505892, 10.41354903,
        9.83639876,  8.71050346, 11.0273912 , 18.39543758, 20.48491277,
       20.29577836,  9.62665083, 16.48729349, 11.45381342, 14.47583552])

In [13]:
lr.score(x_test, y_test)

0.9055637825692336

In [14]:
y_test

65      9.3
137    20.8
78      5.3
128    24.7
81     12.3
114    14.6
138     9.6
90     11.2
180    10.5
179    12.6
12      9.2
27     15.9
82     11.3
32      9.6
94     11.5
7      13.2
92     19.4
55     23.7
177    11.7
30     21.4
152    16.6
158     7.3
141    19.2
146    13.2
103    14.7
118    15.9
117     9.4
167    12.2
161    13.3
72      8.8
73     11.0
143    10.4
164    11.9
14     19.0
0      22.1
54     20.2
145    10.3
194    17.3
80     11.8
83     13.6
Name: sales, dtype: float64